name: R-CMD-check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, r: '4.4.1' }
          - { os: macOS-latest, r: '4.4.1' }
          - { os: windows-latest, r: '4.4.1' }

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up R
        uses: r-lib/actions/setup-r@v3
        with:
          r-version: ${{ matrix.config.r }}

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev
        if: runner.os == 'Linux'

      - name: Install R package dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install rcmdcheck
        run: |
          install.packages('rcmdcheck')
        shell: Rscript {0}

      - name: Run R CMD check
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
